- components/Search.tsx
- cypress/integration/search.ts
- package.json
- yarn.lock
Store state in the router to keep routes and state in sync.
Using `next-usequerystate`. This simplifies syncing state and URL for queries. This pill request also fixes the "flicker" (running two queries) when faceting results
> Store state in the router

- .travis.yml
- cypress/integration/doiContainer.test.ts
- cypress/integration/search.test.ts
- package.json
- src/components/Doi/Doi.test.tsx
- src/components/Doi/Doi.tsx
- src/components/DoiContainer/DoiContainer.tsx
- src/components/DoiMetadata/DoiMetadata.test.tsx
- src/components/DoiMetadata/DoiMetadata.tsx
- src/components/Search/Search.tsx
- src/styles.css
- yarn.lock
Display language facet. Also display tags for language, resourceTypeGeneral, and field of science.
Implement language facet the same way as the other facets. Also adding tags using the `label` bootstrap style.
> Display language facet and tags

- .travis.yml
- cypress/integration/doiContainer.test.ts
- cypress/integration/search.test.ts
- src/components/DoiContainer/DoiContainer.tsx
- src/components/DoiMetadata/DoiMetadata.tsx
- src/components/Search/Search.tsx
- src/styles.css
Add a license facet and display license for each content item.
Licenses are normalized in the GraphQL API using SPDX.
> License facet and display in GraphQL. #42

- src/components/TypesChart/TypesChart.test.tsx
- src/components/TypesChart/TypesChart.tsx
Component to create donut chart for resource type based on graphql response. 
- includes tootips and legend for the types
addresses: https://github.com/datacite/akita/issues/39
To review this PR, please:
1. pull the PR and run the code locally
2. run **yarn run cypress open** to see the visualisation 
Thanks
- Adding it into the person and organisation pages will be addresses is respective PRs
- We might consider to change the color palette in the future.
> Feature: types chart

- .eslintrc.js
- src/components/FilterItem/FilterItem.tsx
- src/components/Organization/Organization.tsx
- src/components/OrganizationContainer/OrganizationContainer.tsx
- src/components/OrganizationMetadata/OrganizationMetadata.tsx
- src/components/Search/Search.tsx
- src/components/SearchOrganization/SearchOrganization.tsx
- src/pages/organization/[organization].tsx
- src/styles.css
- src/utils/helpers.tsx
This is to create new organisations search and organisations display.
Added search inline with other existing searches
Added organisation display with works display in line with other components:
At the moment I've kept the OrganizationContainer as the one that handles displaying related works as this is temporarily cleaner.
I'd like to actually move the related works into a seperate "Works" component that then renders the metadata, this could be used for the details pages of Person and Organization.
TODO
Considerations of how to handle components, ideally they should be isolated and only contain the data and types they need to function, especially when working with presentational components only.
> Add organisations search and display

- cypress/fixtures/licenseChart.json
- src/components/LicenseChart/LicenseChart.test.tsx
- src/components/LicenseChart/LicenseChart.tsx
- src/components/OrganizationContainer/OrganizationContainer.tsx
- src/components/Person/Person.tsx
- src/components/PersonContainer/PersonContainer.tsx
- src/components/ProductionChart/ProductionChart.tsx
- src/components/TypesChart/TypesChart.test.tsx
- src/components/TypesChart/TypesChart.tsx
- src/styles.css
Show donut chart of license information, similar to work type.
Reuse donut chart. Calculate missing value count. Adjust donut chart size and bar chart width. Do the same chart(s) for organization display.
> Visualize license information

- src/components/WorkContainer/WorkContainer.tsx
- src/components/WorkMetadata/WorkMetadata.tsx
- src/styles.css
Provide direct link to PDF if content is from Crossref and PDF link returned from Unpaywall API.
closes: #114
Implemented in the GraphQL API as `contentUrl` field. Only check for single DOI pages but not queries, as this requires a live API call to Unpaywall.
> Provide download link for single doi

- .env
- cypress/fixtures/person.json
- cypress/integration/personContainer.test.ts
- src/components/Person/Person.tsx
- src/components/PersonContainer/PersonContainer.tsx
- src/components/PersonEmployment/PersonEmployment.test.tsx
- src/components/PersonEmployment/PersonEmployment.tsx
- src/components/WorkMetadata/WorkMetadata.tsx
- src/pages/_app.tsx
Show employment section on the person page, fetching the data from the person's ORCID record. In addition we are linking to the organization page for the employer.
closes: #116
Do a second API call to the ORCID REST API to fetch employment information (in addition to the `/person` endpoint). In the GraphQL API, use a Wikidata SPARQL query to find the ROR ID for an employer. Use a feature flag and only show this on stage.
- Ensure you give reasons for the changes you are …
> Show person employment with links to organizations

- cypress/integration/fundrefContainer.test.ts
- cypress/integration/gridContainer.test.ts
- src/components/OrganizationContainer/OrganizationContainer.tsx
- src/pages/doi.org/[...doi].tsx
- src/pages/grid.ac/[...grid].tsx
Facilitate crosslinking within DataCite Commons when only external organization identifiers are known, e.g. Crossref Funder ID for funding in work metadata, or GRID ID for person employments. This avoids the overhead of mapping the identifiers in the API. This feature also facilitates incoming links to DataCite Commons.
closes: #118
Run the GraphQL query with the external identifier. Use the router to push to the default path for an organization once the ROR ID is known from the GraphQL query.
- Offer suggestions on how to improve code e.g. …
> Support for external organisation id in path

- cypress/fixtures/doi.json
- cypress/integration/workContainer.test.ts
- src/components/Work/Work.tsx
- src/components/WorkContainer/WorkContainer.tsx
- src/components/WorkFunding/WorkFunding.tsx
- src/pages/_app.tsx
- src/utils/helpers.tsx
Show funding information for a specific work, and link to funder organization page in `akita` if a Crossref Funder ID is included. This works for both Crossref and DataCite DOIs and implements bi-directional linking (funder => works, and work => funder).
closes: #120
Use `WorkFunding` component. Link to funding organization using the Crossref Funder ID and the support for external organizational identifiers implemented in #118.
- Ensure you give reasons for the changes …
> Show funding information per work. 

- cypress/fixtures/doi.json
- cypress/integration/workContainer.test.ts
- hooks/withApollo.ts
- src/components/PersonEmployment/PersonEmployment.tsx
- src/components/SearchWork/SearchWork.tsx
- src/components/Work/Work.tsx
- src/components/WorkContainer/WorkContainer.tsx
- src/components/WorkFunding/WorkFunding.tsx
- src/components/WorkPerson/WorkPerson.test.tsx
- src/components/WorkPerson/WorkPerson.tsx
- src/styles.css
- tsconfig.json
Show additional information about people per DOI: contributors and affiliations.
closes:  #128
Add new sections for creators and contributors in tabular format. This also helps with ORCID claiming, as we can link the claim to a specific author. To avoid long lists of creators, contributers (and funding), we arrange them in three columns.
> Show affiliation for creators and contributors

- src/components/Consent/Consent.tsx
- src/styles.css
closes: Issue #1151.  Makes the accept/reject cookie buttons available on mobile devices down to 360px wide screens.
Added new css for mobile sized screens.  Set parameters appropriately for react-cookie-consent package which controls the cookie consent bar.
Testing for different screen sizes by someone other than myself.
Check over the format and let me know if there are other changes needed.
The style.css changes are at the end of the file.  Most of the changes there are linting changes for indentation or adding/deleting blank lines, inadvertantly made by my editor.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language …
> Mobile cookie banner

- config/links.yml
- src/components/Footer/Footer.tsx
DataCite footer link for "staff" transitioned to 'team' some time ago. Catching this app up.
> 'Staff' link has transitioned to 'Team' in most footers

- src/components/VerticalBarChart/VerticalBarChart.test.tsx
- src/components/VerticalBarChart/VerticalBarChart.tsx
Bar chart on the vertical access to show categorical distributions (such as facets)
addresses: https://github.com/datacite/datacite/issues/1345
addresses: https://github.com/datacite/datacite/issues/1366
Using vega and square root scales, and missing bar
> Vertical chart for metadata distributions

- package.json
- yarn.lock
There was an error on deployment to vercel with regards to font-awesome and react.
Specifically 'IconDefinition' is not assignable to type 'IconProp'
[Type 'IconDefinition' is not assignable to type 'IconProp' with Typescript](https://github.com/FortAwesome/react-fontawesome/issues/366#)
As outlined in the above link, we had two versions of font-awesome-common-types that were in conflict with eachother.
Specify the resolution of font-awesome-common-types in package.json should fix this.
- Offer suggestions on how to improve code e.g. simplification or …
> Needed to specify font-awesome-common-types in package.json

- cypress/integration/OrganizationContainerMissingGridID.test.ts
- src/components/OrganizationMetadata/OrganizationMetadata.tsx
Fix a bug where the GridID was assumed to exists.  Handles the case where it does not.
closes: #213
Wraps checks that the array of grid ids is larger than 0 before trying to render a link to a grid identifier.
> Display GridID only if it exists in metadata

- src/components/Claim/Claim.tsx
The color of the claim button is that of a info-label while the rest of fabrica uses 'defaul-label' for this buttons (secondary)
Change the class.
> Consisten button UI in Commons

- src/components/FacetList/FacetList.tsx
- src/components/FairFilter/FairFilter.tsx
- src/components/RepositoryDetail/RepositoryDetail.tsx
- src/components/SearchRepository/SearchRepository.tsx
- src/utils/apolloClient.ts
Facets in repository search were showing some strange behavior.  Many were displaying the same values when they should not.
This PR fixes that by configuring the Apollo client to not cache facets.
Also, the conditional display of contacts was not working in the repository display.
This was because in JavaScript, an empty array is a truethy value.  The solution is to query if `dataArray?.lenth>0`
> Unique keys

- src/components/RepositoryDetail/RepositoryDetail.tsx
- src/pages/repositories/[repoid].tsx
OpenGraphTags and title were not rendering in the <head> element for repository detail pages.
closes: #228 
The title and meta tags must be direct children of the next/head tag.  Moved the next/head tag into the RepositoryHeadInfo tag.
https://nextjs.org/docs/api-reference/next/head
> Move next/head tag into RepositoryHeadInfo

- package.json
- yarn.lock
Since the last release with dependency upgrades, issue https://github.com/datacite/datacite/issues/1702 has occurred.
It seems to be a problem with the `jsonwebtoken` dependency (see linked issue for details), which was updated in the last release. This PR rolls back to the previous version.
closes: https://github.com/datacite/datacite/issues/1702
> Rollback jsonwebtoken to 8.5.1

- src/components/Claim/Claim.module.scss
- src/components/Claim/Claim.tsx
Fixed claim button styles when signed in
> fair vis release 1 - fixed claim button styles

- src/components/WorkFacets/WorkFacets.tsx
Removes the new other and missing counts from the Work Types and License filter lists
closes: https://github.com/datacite/datacite/issues/1896
> Removed other and missing from filter lists

- src/components/ExampleText/ExampleText.tsx
- src/pages/doi.org/index.tsx
- src/pages/index.tsx
- src/pages/orcid.org/index.tsx
- src/pages/repositories/index.tsx
- src/pages/ror.org/index.tsx
Replaces the current info box on Works, People, Organization, and Repository index pages with a more descriptive panel that includes search examples
closes: datacite/datacite#1912
> Updated example text on each index page

- src/components/HorizontalStackedBarChart/HorizontalStackedBarChart.tsx
- src/components/WorksListing/WorksListing.tsx
- src/pages/doi.org/[...doi].tsx
- src/pages/orcid.org/[orcid].tsx
- src/pages/ror.org/[rorid].tsx
- Moved charts to related works section
- Tweaked HorizontalBarChart spec
- Updated tooltip
- Removed legend header
> Move related works charts

- src/utils/apolloClient.ts
Apollo was caching values for multifacets, this is not desirable.  They should be treated much like regular facets.
Disables inMemoryCache for multiFacets in the ApolloClient config.
> Do not cache multifacet values in memory

- src/pages/doi.org/[...doi].tsx
- src/pages/orcid.org/[orcid].tsx
- src/pages/ror.org/[rorid].tsx
Currently, all of the data is fetched in one big pass. These changes split up the query into two separate queries that can run in parallel, allowing it to quickly fetch and show the metadata for the DOI, organization, or person, while loading the related content.
Additionally, if an error occurs during the related content loading, the metadata section will still be shown, and an error message will only be shown in the related content section.
For each page, the query has been split up into two queries, metadata and related content, that run in parallel. They each have their own rendering and handling logic
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias …
> Separate loading and error handling for DOI, Organization, and Person pages

- src/middleware.ts
- src/pages/doi.org/[...doi].tsx
- src/pages/ror.org/[rorid].tsx
- src/utils/helpers.ts
Bots no longer see Download Reports section on DOI and organization pages. Also fixed middleware failing during build step
The middleware was failing in the build step due to incompatibility with the bable plugin istanbul. Adding a line to ignore it at the top of the file, as well as moving the related isBot function into the middleware file, resolved the issue. 
> Fixed middleware and added more bot download prevention

- src/components/SankeyGraph/SankeyGraph.tsx
Sankey charts may have wrong bar heights
This change fixes that
> Fix Sankey chart bug

- .github/workflows/codeql-analysis.yml
- .github/workflows/cypress_tests.yml
- .github/workflows/deploy.yml
- .github/workflows/manual.yml
- .github/workflows/release.yml
This pull request updates various GitHub Actions to newer versions.
The checkout action was updated from v3 to v4. The setup-node action was updated from v3 to v4. The github-action from cypress-io was updated from v5 to v6. The vercel-action from amondnet was updated from v25.1.0 to v25.2.0.
Monitor the actions after merging to ensure they are still running correctly.
To ensure the latest features, security updates, and bug fixes from these Github Actions are utilised. …
> Update GH Actions

- package.json
- src/app/Providers.tsx
- src/utils/apolloClient/builder.ts
- src/utils/apolloClient/provider.tsx
- yarn.lock
The Apollo client was re-rendering unnecessarily
Updated the client to use the [experimental NextJS app router package](https://github.com/apollographql/apollo-client-nextjs)
> Replaced apollo client with experimental nextjs app router version

- src/app/doi.org/[...doi]/RelatedContent.tsx
- src/components/WorkFacets/WorkFacets.tsx
- src/components/WorksListing/WorksListing.tsx
- src/data/queries/doiQuery.ts
- src/data/types.ts
Display all related works (as exposed through events) as the default option
closes: datacite/datacite#2176
Queries graphql for all related dois (regardless of specific relationship) and displays this as the default filter.
> Add All option to related works filters

- src/app/doi.org/[...doi]/page.tsx
Do not filter which resourceTypes display a network graph
closes: #381 
Remove clause that checks the resourceType before rendering the graph
> All resourceTypes display a network Graph

- src/components/License/License.tsx
- src/styles.css
closes: datacite/datacite#2192
Use \<img\> tag instead of NextJS \<Image\>, which has requirements around including height and width in some circumstances. 
> Fix for license image stretching

- src/data/queries/doiQuery.ts
- src/utils/fetchConditionalCache.ts
Improve data fetching with conditional caching for DOI queries to optimize performance and reduce unnecessary network requests.
Implement a custom `fetchConditionalCache` utility function to handle conditional caching for fetch requests, specifically for DOI data retrieval.
- Created a new `fetchConditionalCache.ts` utility function
- Modified `doiQuery.ts` to use the new conditional caching fetch method
- Added default cache revalidation of 1 hour
- Implemented flexible caching options
- Introduces a custom fetch wrapper that:
- Allows configurable cache revalidation
- Defaults to 1-hour cache if no revalidation time is specified
- Handles failed requests gracefully
- Uses Next.js fetch caching mechanism
- Provides flexibility in cache configuration through optional parameters
- Be …
> Add Conditional Caching for DOI Fetch Requests

- cypress/e2e/searchOrganization.test.ts
- cypress/e2e/searchPerson.test.ts
- cypress/e2e/searchWork.test.ts
- src/components/NoResults/NoResults.tsx
- src/components/SearchOrganization/SearchOrganization.tsx
- src/components/SearchPerson/SearchPerson.tsx
- src/components/SearchRepository/SearchRepository.tsx
- src/components/SearchWork/SearchWork.tsx
- src/components/WorksListing/WorksListing.tsx
- src/data/queries/searchDoiFacetsQuery.ts
- src/data/queries/searchDoiQuery.ts
Improve error handling and response processing in DOI search and facets queries to provide more informative error messages and ensure proper error propagation.
The changes enhance the error handling mechanism for DOI search and facets API requests by:
- Adding explicit error checking for API responses
- Throwing meaningful error messages when requests fail
- Ensuring that errors are properly propagated through the query function
- Added response status checking in `fetchDois` and `fetchDoisFacets` functions
- Implemented custom error message generation based on API response
- Removed try-catch blocks in favor of direct error throwing
- Ensured that error messages include both API-provided error titles and fallback status code messages
- Standardized the "No results" alert across different …
> Enhance DOI Search Error Handling

- src/components/RepositoryDetail/RepositoryDashboard.tsx
Add a null check for `repoId` in the RepositoryDashboard component to prevent rendering when no repository ID is provided.
- Added an early return condition to prevent rendering when `repoId` is falsy (null, undefined, empty string)
- Ensures component gracefully handles cases with no repository ID
- Simple null check prevents potential undefined errors
- Minimal change that improves component's robustness
- Prevents unnecessary API calls or rendering when no valid repository ID exists
- Offer suggestions on how to improve code e.g. simplification or …
> Add null check for repoId in RepositoryDashboard

- src/app/ror.org/page.tsx
- src/components/Header/Search.tsx
- src/data/queries/searchOrganizationQuery.ts
Addresses issue #454: Search Functionality Causing Full Page Reload and React Query Cache Invalidation
The PR aims to improve the search experience across different search types (works, people, organizations, and repositories) by optimizing the search functionality and preventing unnecessary page reloads.
The changes focus on enhancing the search component's behavior and ensuring a smoother user experience:
- Added an effect to synchronize search input with URL parameters
- Modified search function to prevent default form submission
- Adjusted debounce delay for more responsive search
- Updated page component naming for clarity
- Removed unnecessary console.log
- Added `useEffect` to update search input when URL changes
- Increased debounce delay from 300ms to 500ms
- Prevented default …
> Fix search functionality to prevent full page reload

- src/data/queries/doiQuery.ts
This PR updates the DOI query to correctly search for DOIs by wrapping the ID in quotes.
closes datacite/datacite/issues/2289
The change modifies the `buildDoiSearchParams` function to include the DOI ID in quotes when constructing the query string. This ensures that the search accurately targets the specified DOI.
- Updated the `query` parameter in `buildDoiSearchParams` to wrap the DOI id in quotes: `query: \`uid:"${id}"\``
- The change ensures that the DOI ID is treated as a literal string when querying the API. This is necessary for accurate matching.
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral language appearing …
> Fix: DOI query with quotes

- yarn.lock
This PR updates the project dependencies, specifically upgrading Next.js to a newer patch version.
The `yarn.lock` file has been updated by running `yarn install` to reflect the latest versions of specified dependencies, most notably Next.js and its related packages.
*   Updated `next` from `14.2.25` to `14.2.28`.
*   Updated `@next/env` from `14.2.25` to `14.2.28`.
*   Updated various `@next/swc-*` packages from `14.2.25` to `14.2.28`.
*   Updated `caniuse-lite` and `nanoid` dependencies.
*   Modified the `yarn.lock` file to reflect these version changes and updated integrity hashes.
This is a routine dependency update to pull in the latest patch releases for Next.js and other packages. Patch releases primarily contain bug fixes and minor improvements.
- Be humble in the language and …
> Bump Next.js to 14.2.28 and update dependencies
