cypress/integration/doiContainer.test.ts, src/components/CitationFormatter/CitationFormatter.tsx, src/components/ContentItem/ContentItem.test.tsx, src/components/ContentItem/ContentItem.tsx, src/components/Doi/Doi.test.tsx, src/components/Doi/Doi.tsx, src/components/DoiContainer/DoiContainer.tsx, src/components/Search/Search.tsx, src/pages/dois/[doi].tsx, src/styles.css
Clean up after merging components and changing folder structure.
=> Align components

src/components/Search/Search.tsx
Support filtering by OECD Field of Science.
=> Add field of science facet

.travis.yml, package.json, src/components/CitationsChart/CitationsChart.tsx, src/components/ContentItem/ContentItem.tsx, src/components/Doi/Doi.test.tsx, src/components/Doi/Doi.tsx, src/components/DoiContainer/DoiContainer.tsx, src/components/DoiMetadata/DoiMetadata.test.tsx, src/components/DoiMetadata/DoiMetadata.tsx, src/components/Header/Header.tsx, src/components/Search/Search.tsx, src/components/UsageChart/UsageChart.test.tsx, src/components/UsageChart/UsageChart.tsx, yarn.lock
_Describe the problem or feature in addition to a link to the issues._
Add chart for usage stats (downloads and views)
closes: https://github.com/datacite/akita/issues/6
additionally addresses some issues from : https://docs.google.com/document/d/1yT5Kb4RRMyBsUxH3NfCBrv0wvpFQ3l0cHbR0eVBY5WA/edit#heading=h.fn11ewq17fk9
Separated chart for usage type
Additionally there is refactoring of the components
=> Feat usage chart

src/components/CitationsChart/CitationsChart.test.tsx, src/components/CitationsChart/CitationsChart.tsx, src/components/ProductionChart/ProductionChart.test.tsx, src/components/ProductionChart/ProductionChart.tsx, src/components/UsageChart/UsageChart.test.tsx, src/components/UsageChart/UsageChart.tsx
component to create chart for doi production. Includes tootip.
closes: https://github.com/datacite/akita/issues/40
To review this PR, please:
1. pull the PR and run the code locally
2. run **yarn run cypress open** to see the visualisation 
Thanks
- Adding it into the person and organisation pages will be addresses is respective PRs
=> Feature add doi production chart

cypress/integration/personContainer.test.ts, src/components/CitationsChart/CitationsChart.tsx, src/components/DoiMetadata/DoiMetadata.tsx, src/components/Pager/Pager.tsx, src/components/Person/Person.test.tsx, src/components/Person/Person.tsx, src/components/PersonContainer/PersonContainer.tsx, src/components/ProductionChart/ProductionChart.test.tsx, src/components/ProductionChart/ProductionChart.tsx, src/components/Search/Search.tsx, src/components/TypesChart/TypesChart.tsx, src/components/UsageChart/UsageChart.tsx, src/pages/person/[person].tsx, src/styles.css, src/utils/helpers.tsx
Researcher Profile of an individual person.
Detail of all features in: https://github.com/datacite/akita/issues/11
closes: https://github.com/datacite/akita/issues/11
- Abstract pagination component to separate testing
- create helper to  extract orcid
- added links to other profiles
=> Feature person page

src/components/Search/Search.tsx, src/components/SearchContent/SearchContent.tsx, src/components/SearchOrganization/SearchOrganization.tsx, src/components/SearchPerson/SearchPerson.tsx
New sub search components define results/filters and do fetching.
This is a PR to start seperating out the search functionality into distinct components.
More refactoring work will need to happen but this is the basic gist which functionally works and replaces what we have but with optional new components that can be rendered.
Search component doesnt do any data fetch, it just handles search input and state for that search.
Individual search components are for fetching data based on search query and handling individual filters.
N/A
N/A
=> Move search into own component

hooks/withApollo.ts, package.json, src/components/CitationFormatter/CitationFormatter.tsx, src/components/DoiContainer/DoiContainer.tsx, src/components/PersonContainer/PersonContainer.tsx, src/components/SearchContent/SearchContent.tsx, src/components/SearchOrganization/SearchOrganization.tsx, src/components/SearchPerson/SearchPerson.tsx, src/pages/_app.tsx, yarn.lock
See https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/
Mostly everything is now under one package.
To be using latest apollo client 3
Upgrades packages and imports.
=> Upgrade to apollo client 3

cypress/integration/personContainer.test.ts, cypress/integration/searchPerson.test.ts, src/components/DoiMetadata/DoiMetadata.tsx, src/components/Person/Person.test.tsx, src/components/Person/Person.tsx, src/components/PersonContainer/PersonContainer.tsx, src/components/PersonMetadata/PersonMetadata.test.tsx, src/components/PersonMetadata/PersonMetadata.tsx, src/components/Search/Search.tsx, src/components/SearchPerson/SearchPerson.tsx, src/pages/dois/[...doi].tsx, src/pages/people/[person].tsx, src/utils/helpers.tsx
Added results list for searching people and search for people.
Also include additional fixes from other issues
detail: https://github.com/datacite/akita/issues/10
closes: https://github.com/datacite/akita/issues/10
closes: https://github.com/datacite/akita/issues/54
=> Feat search for persons

.travis.yml, cypress/integration/doiContainer.test.ts, cypress/integration/personContainer.test.ts, cypress/integration/search.test.ts, cypress/integration/searchPerson.test.ts, cypress/integration/server.test.ts, package.json, src/components/CitationsChart/CitationsChart.tsx, src/components/Doi/Doi.test.tsx, src/components/Doi/Doi.tsx, src/components/DoiContainer/DoiContainer.tsx, src/components/DoiMetadata/DoiMetadata.test.tsx, src/components/DoiMetadata/DoiMetadata.tsx, src/components/DoiRelatedContent/DoiRelatedContent.test.tsx, src/components/DoiRelatedContent/DoiRelatedContent.tsx, src/components/OrganizationContainer/OrganizationContainer.tsx, src/components/Pager/Pager.tsx, src/components/Person/Person.tsx, src/components/ProductionChart/ProductionChart.tsx, src/components/SearchContent/SearchContent.tsx, src/components/UsageChart/UsageChart.tsx, src/utils/helpers.tsx, tsconfig.json
Add list for citations and references
closes: https://github.com/datacite/akita/issues/12
=> Feat related content list

cypress/integration/doiContainer.test.ts, cypress/integration/personContainer.test.ts, package.json, src/components/DoiContainer/DoiContainer.tsx, src/components/PersonContainer/PersonContainer.tsx, src/components/SearchContent/SearchContent.tsx, src/styles.css, yarn.lock
Add share links for dois and people.
Use `react-share` npm library, and use twitter, facebook and email share button.
=> Add share links for dois and people

cypress/integration/personContainer.test.ts, src/components/DoiContainer/DoiContainer.tsx, src/components/DoiFacet/DoiFacet.tsx, src/components/OrganizationContainer/OrganizationContainer.tsx, src/components/Person/Person.test.tsx, src/components/PersonContainer/PersonContainer.tsx, src/components/ProductionChart/ProductionChart.test.tsx
removes code duplication
encapsulate all facets in a single component for reuse
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
=> refactor: abstracts facets to its own component

package.json, src/components/Layout/Layout.tsx, src/pages/_app.tsx, yarn.lock
Feature flags allow for the more granular release of new features. Our initial implementation will disable unreleased features in production.
closes: #112
Use `flagged` npm library and `NEXT_PUBLIC_API_URL` to check for `stage` vs. `production`. For more complex scenarios going forward we can use env variables.
=> Add support for feature flags

package.json, src/components/Consent/Consent.tsx, src/styles.css, yarn.lock
closes: none
Build didn't work due to 2 versions of Cypress being downloaded.
Modifies package.json to require Cyprus 6.3.0 and yarn.lock to always resolve to that version.
- [ X] Bug fix (non-breaking change which fixes an issue)
=> Fix Cypress versioning in build.

src/components/Person/Person.tsx
it should be `publications` https://www.figma.com/file/LX0jHl9chHKvv430swTpwm/open-access-badge?node-id=243%3A1
=> fixed typo

.github/workflows/pull_request.yml
Currently PRs are not tested.  This can make it difficult to know whether or not to merge them.
This runs all tests for any PR against the master branch.
=> Test pull requests

yarn.lock
Vulnerability reported by dependabot
Initial `yarn audit --group devDependencies` resulted in 1 vulnerabilities
Reported an issue with the dependency's repository
Monitored repository for new release (came in today)
Ran `yarn upgrade`
This updated the yarn.lock file with appropriately updated dependencies.
`yarn audit --group devDependencies` then ran clean with 0 vulnerabilities found.
=> Update @cypress/code-coverage and remove last reported vulnerability

src/components/Work/Work.tsx
our token won't allows to to claim Crossref dois
=> Claiming only for Datacite DOis

src/components/RepositoryDetail/RepositoryDetail.module.scss, src/components/RepositoryDetail/RepositoryDetail.tsx
Display contact information for repository pages when available.
=> Repo detail

src/components/RepositoryDetail/RepositoryDetail.module.scss, src/components/RepositoryDetail/RepositoryDetail.tsx
Add extended metadata for Repository Detail View based on re3Data
=> Add extended metadata for Repository Detail View based on re3Data

yarn.lock
Update critical security dependencies
Initial `yarn audit` resulted in 5 vulnerabilities
Ran `yarn upgrade`
This updated the yarn.lock file with appropriately updated dependencies.
`yarn audit` then ran clean with 0 vulnerabilities found.
=> Updated dependencies using yarn upgrade

.yarnclean, next-env.d.ts, next.config.js, package.json, tsconfig.json, yarn.lock
Upgrade to next v12
closes: #185 
Updates the dependency in package.json and then yarn upgrade.
There were a couple of config changes necessary (in `.yarnclean`)
=> Upgrade to next12

config/links.yml, src/components/Footer/Footer.tsx
Fix wrong link in footer.
closes: https://github.com/datacite/datacite/issues/1445
=> Update Metadata Search link in footer

src/components/WorkMetadata/WorkMetadata.tsx
seeks to address scenario 11. by linking to repository page in commons https://docs.google.com/document/d/18CJvxMPM3jOiMneidiTl43wCdD_D_siwUcY6aihk3-A/edit#heading=h.mk7a5pardqo0
closes: https://github.com/datacite/datacite/issues/1389
part_of: https://github.com/datacite/datacite/issues/1366
=> Link to repository from DOI page. Scenario 11

src/components/Header/Header.tsx, src/components/RepositoryDetail/RepositoryDetail.tsx, src/components/RepositoryMetadata/RepositoryMetadata.tsx, src/components/SearchRepository/SearchRepository.tsx, src/components/SearchWork/SearchWork.tsx
Repository GQL endpoint has changed.
Updates structure of GQL request and variables used by Repositories.
=> New repository gql

src/components/Layout/Layout.tsx
Migrates usersnap classic to the new one
closes: https://github.com/datacite/datacite/issues/1443
https://app.frontapp.com/open/msg_hjmasb9
=> migrating usersnap in commons

src/components/WorkMetadata/WorkMetadata.tsx
Some works were not displaying the link to their associated repository or container.
closes: https://github.com/datacite/datacite/issues/1462
If the `container.title` is missing, skip over the container search and link directly to the repository view.
=> Consistent repository link

src/components/OrganizationMetadata/OrganizationMetadata.tsx
Remove links to non-resolving GRID urls.
closes: #231 
Removes the link.  Keeps the GRID ID
=> Remove link to non-existent grid.ac url.  Keep the identifier

src/components/RepositoryDetail/RepositoryDetail.tsx, src/components/SearchRepository/SearchRepository.tsx, src/pages/repositories/[...repoid].tsx
Fix links to generalist repositories in Commons
closes: https://github.com/datacite/datacite/issues/1573 https://github.com/datacite/datacite/issues/1578
=> Issue 1573 - Fix Links to generalist repositories in Commons

src/components/SearchWork/SearchWork.tsx
Fix the author facet in DOI/works search.
closes: https://github.com/datacite/datacite/issues/1499
Appends any filterQuery URL parameters to the general query sent through the GQL query.
Note: This could be addressed later by amending the GQL endpoint in lupo to allow an author parameter.
=> Amend the works query statement if user selects author's facet

package.json, src/components/AuthorsFacet/AuthorsFacet.tsx, src/components/Consent/Consent.tsx, src/components/WorkPerson/WorkPerson.tsx, yarn.lock
Additional dependency upgrades.
Minor tweaks to allow the build to finish.
=> Dependencies

.github/workflows/codeql-analysis.yml, .github/workflows/cypress_tests.yml, .github/workflows/deploy.yml, .github/workflows/manual.yml, .github/workflows/release.yml
Upgraded GitHub actions to use Node.js 16, due to the warnings each deployment.
closes: #239 
Updated the current actions from v2 to v3
=> Upgrade versions of checkout and cypress actions.  Remove slack action.

cypress/integration/fundrefContainer.test.ts, cypress/integration/gridContainer.test.ts, cypress/integration/organizationContainer.test.ts, src/components/Organization/Organization.tsx, src/components/OrganizationMetadata/OrganizationMetadata.tsx, src/styles.css
[VERCEL BUILD](https://akita-c1mmqvnkg-datacite.vercel.app/)
Add a summary of relevant statistics to the top of the Organization page. It includes counts for works, citations, views, and downloads. Citations, views, and downloads also include a help icon that links to the corresponding support page.
> Note that I have fabricated the counts of views and citations in the image above for demonstration, because many organizations in staging don't have those. In the vercel build we will only see the counts of Works and Citations for this organization
closes: datacite/datacite#1728
There was already a very similar component that exist in the Organization component. I moved that to the top of the page, and reformatted it to match the wireframe.
- Be humble in the language and feedback you give, …
=> Fair visualizations feature 3 - summary measures stats

src/components/WorkPerson/WorkPerson.tsx
Corrects formatting for creators and contributors with multiple affiliations so they are not listed on one line. 
closes: #251 
Wraps affiliations in separate divs. 
=> Corrects formatting for creators and contributors with multiple affiliations  

cypress/integration/workContainer.test.ts, src/components/CitationFormatter/CitationFormatter.tsx, src/components/CiteAs/CiteAs.tsx, src/components/MetadataTable/MetadataTable.tsx, src/components/PersonTable/PersonTable.tsx, src/components/Title/Title.module.scss, src/components/Title/Title.tsx, src/components/Work/Work.tsx, src/components/WorkMetadata/WorkMetadata.tsx, src/components/WorkPerson/WorkPerson.tsx, src/pages/doi.org/[...doi].tsx
- Moves the Cite As section to the left sidebar
- MetadaDisplay for DOIs now shows creators and contributors as tables
- Updated the look of the title for DOIs
=> Fair Visualization release 1 - additional changes

src/components/MetricsCounter/MetricsCounter.tsx
Removed hardcoded values left over from testing
=> fair vis release 1 - removed hardcoded test values

.github/workflows/deploy.yml, .github/workflows/manual.yml, .github/workflows/release.yml
Removed unused steps in GH actions.  Simplify passing secrets to sub-actions.
=> Inherit secrets in GH actions.  Remove "Extract variables" step as it was not used

src/components/Layout/Layout.tsx
closes: #263.   See the issue.
Copy shared assets from www.datacite.org to assets.datacite.org/assets.stage.datacite.org and change any references to them.
=> Use shared assets from assets.datacite.org

src/components/DoiDashboard/DoiDashboard.tsx, src/components/DonutChart/DonutChart.tsx, src/components/ForceDirectedGraph/ForceDirectedGraph.tsx, src/components/HelpIcon/HelpIcon.tsx, src/components/HorizontalStackedBarChart/HorizontalStackedBarChart.tsx, src/components/MetricsDisplay/MetricsDisplay.tsx, src/components/OrganizationDashboard/OrganizationDashboard.tsx, src/components/SankeyGraph/SankeyGraph.tsx, src/components/WorksDashboard/WorksDashboard.tsx, src/pages/doi.org/[...doi].tsx, src/pages/ror.org/[rorid].tsx
Created front ends for the horizontal stacked bar chart, force directed graph, and sankey graph. Added a new component for the DOI and organization page dashboards that show the new graphs.
closes: datacite/datacite#1731, datacite/datacite#1735, datacite/datacite#1777, datacite/datacite#1787
=> Fair Visualization - Works Dashboard (front end)

.github/workflows/cypress_tests.yml, .github/workflows/pull_request.yml
Tests the akita codebase using node 18.
Explicitly sets the node version for cypress tests.
=> Test using node 18

src/components/AuthorsFacet/AuthorsFacet.tsx, src/components/SearchWork/SearchWork.tsx, src/components/WorkFacets/WorkFacets.tsx
=> Fair Visualization Feature 4

cypress/integration/searchWork.test.ts, src/components/AuthorsFacet/AuthorsFacet.tsx, src/components/HelpIcon/HelpIcon.tsx, src/components/HorizontalStackedBarChart/HorizontalStackedBarChart.module.scss, src/components/HorizontalStackedBarChart/HorizontalStackedBarChart.tsx, src/components/WorkFacets/WorkFacets.tsx, src/components/WorksDashboard/WorksDashboard.module.scss, src/components/WorksDashboard/WorksDashboard.tsx
Addresses feedback from [this document](https://docs.google.com/document/d/1aluEXh_7_nsALer7IMCdLiofwWGfAQSLmDDfXYvoE_I/edit)
=> Fair visualization release 2 feedback updates

cypress/integration/personContainer.test.ts, src/components/MetricsDisplay/MetricsDisplay.tsx, src/components/RepositoryDetail/RepositoryDetail.tsx, src/pages/orcid.org/[orcid].tsx
Replaces the donut charts on the People and Repository pages with the new bar chart. Also replaces use of 'deposit' with 'work'
=> Consistently use bar charts

src/components/EmptyChart/EmptyChart.tsx, src/components/SankeyGraph/SankeyGraph.module.scss, src/components/SankeyGraph/SankeyGraph.tsx, src/components/SankeyGraph/SankeySpec.ts, src/components/SearchWork/SearchWork.tsx, src/components/WorksDashboard/WorksDashboard.tsx, src/components/WorksListing/WorksListing.tsx, src/pages/doi.org/[...doi].tsx, src/pages/orcid.org/[orcid].tsx
Adds the Sankey visualization to the DOI page
closes: datacite/datacite#1787
=> Fair vis feature 11 (Sankey chart)

src/components/PersonTable/PersonTable.tsx
Fixes a typo, just one character.
=> Fix typo in PersonTable links

yarn.lock
=> Package upgrades

yarn.lock
This reverts commit a41929225c58d34a3d9e0b63d639d0c73abc5b48.
Reverts depenencies that caused issues outlined in https://github.com/datacite/datacite/issues/1933
=> Revert "Package upgrades (#287)"

src/pages/doi.org/[...doi].tsx
Adds the Sankey chart to the Project DOI page
closes: datacite/datacite#1927
=> Fair Workflows Feature 4 - Related Works people/output types visualization (Sankey chart)

src/pages/doi.org/[...doi].tsx
=> Added related works header

cypress/integration/workContainer.test.ts, src/components/DownloadReports/DownloadReports.tsx, src/components/WorkFacets/WorkFacets.tsx, src/components/WorksListing/WorksListing.tsx, src/pages/api/download-reports/doi/related-works.ts, src/pages/api/download-reports/ror/funders.ts, src/pages/api/download-reports/ror/related-works.ts, src/pages/doi.org/[...doi].tsx, src/pages/ror.org/[rorid].tsx
Implements features 1 and 4 of FAIR Workflows
=> Fair Workflows Release 1

src/data/color_palettes.ts
Adds Vega color assignments for Schema 4.5 resourceTypeGeneral additions.
closes: #311 
=> Adds Vega color assignments for Schema 4.5 resourceTypeGeneral additions

src/pages/doi.org/[...doi].tsx, src/pages/orcid.org/[orcid].tsx, src/pages/ror.org/[rorid].tsx
Currently, when web crawlers access doi, ror, and orcid pages, they needlessly fetch all of the data. This will prevent them from fetching the data for related works.
The page will now check the headers to see if the userAgent is a web crawler. If it is, it will use a lightweight version of the graphQL call, which doesn't include the data for related works
=> Prevent web crawlers from fetching unnecessary data on /doi.org, /ror.org, and /orcid.org pages

src/middleware.ts, src/pages/doi.org/[...doi].tsx, src/pages/orcid.org/[orcid].tsx, src/pages/ror.org/[rorid].tsx, src/utils/helpers.ts
Moved the isBot check logic into middleware, so it can now be used from any page. Additionally, added a custom isBot check to include the GoogleOther bot
[Google bot reference](https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#google-inspectiontool)
=> Moved isBot check into middleware

src/pages/statistics.tsx
Create statistics page at request time instead of build time.
Switch from getStaticProps to getServerSideProps.
=> Revert statistics page

cypress/integration/server.test.ts, src/utils/apolloClient.ts
closes: https://github.com/datacite/akita/issues/324
=> Added operation name to the query param

vercel.json
Serverless functions are called every time a doi page is requested.
This PR reduces the ammount of memory used by the serverless function by 50%
This should theoretically increase the nubmer of requests per month we can make at the included rate without reducing the performance of the serverless function.
Specify the ammount of memory allocated the doi view page.
https://sivarampg.medium.com/simple-effective-way-to-get-upto-8x-more-serverless-function-invocations-gb-hrs-on-vercels-6512031ac7eb
https://vercel.com/docs/functions/serverless-functions#bundling-serverless-functions
- Consider using positive language as opposed to neutral when offering feedback. This is to avoid the negative bias that can occur with neutral …
=> Reduce Memory for Serverless Function

vercel.json
Fixes a typo in the configuration file
=> Fix Typo in vercel function name

src/components/CitationFormatter/CitationFormatter.tsx, src/components/OrganizationDashboard/OrganizationDashboard.tsx, src/components/SearchOrganization/SearchOrganization.tsx, src/components/SearchPerson/SearchPerson.tsx, src/pages/api/download-reports/doi/related-works.ts, src/pages/api/download-reports/ror/funders.ts, src/pages/api/download-reports/ror/related-works.ts, src/pages/doi.org/[...doi].tsx, src/pages/grid.ac/[...grid].tsx, src/pages/orcid.org/[orcid].tsx, src/pages/ror.org/[rorid].tsx
closes: https://github.com/datacite/akita/issues/327
=> Add unique and related names to the GraphQL queries

src/components/SankeyGraph/SankeyGraph.module.scss, src/components/SankeyGraph/SankeySpec.ts, src/components/WorksListing/Server.tsx
=> Fixed sankey loading bug

vercel.json
=> Increased vercel function timeout to 8 seconds

vercel.json
closes: https://github.com/datacite/datacite/issues/2107
=> Increased Vercel function timeout for reports

vercel.json
=> Increased Vercel download reports timeout to 30s

src/components/Claim/Claim.tsx, src/utils/server/session.ts
DOIs that included the Claim button would throw an error
The Claim component had hooks after early returns. This moved the returns to after the hooks.
Also fixed session bug for app router
=> Logged in bug

src/app/Header.tsx, src/app/layout.tsx
=> Moved session into client

src/app/doi.org/[...doi]/page.tsx, src/app/orcid.org/[orcid]/page.tsx
closes: datacite/datacite#2128
=> Fix schemaOrg script

src/components/ClaimStatus/ClaimStatus.tsx
Updates ClaimStatus element for styling consistency when press `Add to ORCID Record` button. See https://akita-pvwyz2gm5-datacite.vercel.app/ to test.
Switches from `Label` to `Button`.
=> Updates ClaimStatus element for styling consistency

src/components/Claim/Claim.tsx, src/components/ClaimStatus/ClaimStatus.tsx, src/components/WorkMetadata/WorkMetadata.tsx
Makes ClaimStatus a label or button depending on a `type` prop to better fit stylistically in WorkMetadata and Claim.
=> Conditional ClaimStatus presentation

vercel.json
Extends the time limit for the related-works-download api call.
closes: datacite/datacite#2152
=> Update vercel config to use app router path

api/app.py
=> Patch: Explicitly disable the flask debugger

.github/workflows/pull_request.yml
PRs should trigger a vercel deployment with an appropriately named alias
=> Update PR action to trigger Vercel Deployment with alias

src/app/doi.org/[...doi]/RelatedAggregateGraph.tsx, src/app/doi.org/[...doi]/page.tsx, src/utils/helpers.ts
Endable dashboards for awards and grants
closes: #377 
Add an additional clause for whether to display Sankey and RelatedAggregate Graphs
=> Enable dashboards for awards and grants

src/app/doi.org/[...doi]/Content.tsx, src/components/DownloadMetadata/DownloadMetadata.tsx, src/components/RepositoryDetail/RepositoryDetail.module.scss, src/components/RepositoryDetail/RepositoryDetail.tsx, src/styles.css
Adds a few smaller tweaks to maintain continuity with current Bootstrap 3 styling.
=> Styling tweaks for Bootstrap 4

src/app/doi.org/[...doi]/Content.tsx, src/components/DownloadMetadata/DownloadMetadata.tsx, src/components/RepositoryDetail/RepositoryDetail.module.scss, src/components/RepositoryDetail/RepositoryDetail.tsx, src/components/Work/Work.tsx, src/styles.css
Styling tweaks for continuity with BS4.
=> Styling tweaks for continuity with BS4

src/app/doi.org/[...doi]/RelatedAggregateGraph.tsx, src/app/doi.org/[...doi]/page.tsx
Limit the rendering of the connected doi graph to non-bots
=> Only render the connected graph for non-bots

vercel.json
Most of our errors in the vercel logs indicate a funciton timout.
Let's see if allowing a bit more time solves the majority of these.
The underlying issue is that the API needs to be faster.
Increases the time allowed for App router routes.
=> Increase function timeout time for app router pages

src/components/License/License.module.scss, src/components/Title/Title.module.scss, src/components/Title/Title.tsx
Resize licenses to work with BS4 styling
=> Resize licenses

src/app/doi.org/[...doi]/page.tsx
closes: datacite/datacite#2211
=> fixed datacite#2211

src/app/layout.tsx
=> re-introduced feedback button

public/robots.txt
Disallow all bots and remove the sitemap in `robots.txt` to prevent all bots from crawling commons
=> Disable all bots and remove sitemap

next.config.js
=> removed sitemaps rewrite

src/app/doi.org/[...doi]/RelatedAggregateGraph.module.scss, src/app/doi.org/[...doi]/RelatedAggregateGraph.tsx
Updates explanatory text and display for network graph. See discussion here: https://datacite.slack.com/archives/C07K4KRNRL3/p1730206752621679
=> Updates explanatory text and display for network graph

src/app/doi.org/[...doi]/Content.tsx, src/app/doi.org/[...doi]/RelatedContent.tsx, src/app/doi.org/[...doi]/mapSearchParams.ts, src/app/doi.org/[...doi]/page.tsx, src/components/DownloadMetadata/DownloadMetadata.tsx, src/components/DownloadMetadata/ExportMetadata.tsx, src/components/DownloadReports/DownloadReports.tsx, src/components/Header/ClientButtons.tsx, src/components/Header/Header.tsx, src/components/Header/ServerButtons.tsx, src/components/MetadataTable/MetadataTable.tsx, src/components/MetricsCounter/MetricsCounter.tsx, src/components/ReactBootstrap.tsx, src/components/ShareLinks/ShareButtons.tsx, src/components/ShareLinks/ShareLinks.tsx, src/components/Title/Title.tsx, src/components/Work/AnalyticsBar.tsx, src/components/Work/Work.tsx, src/components/WorkMetadata/WorkMetadata.tsx
=> refactor to RSC

src/data/queries/organizationRelatedContentQuery.ts
=> fix incorrect gql query

src/app/doi.org/[...doi]/Content.tsx, src/app/doi.org/[...doi]/RelatedContent.tsx, src/app/ror.org/[rorid]/Content.tsx, src/app/ror.org/[rorid]/RelatedContent.tsx, src/app/ror.org/[rorid]/mapSearchParams.ts, src/app/ror.org/[rorid]/page.tsx, src/components/Organization/Organization.tsx, src/components/OrganizationMetadata/OrganizationMetadata.tsx, src/components/Title/Title.tsx
=> refactor organization page for RSC

src/app/doi.org/[...doi]/Content.tsx, src/app/doi.org/[...doi]/page.tsx, src/app/orcid.org/[orcid]/Content.tsx, src/app/orcid.org/[orcid]/page.tsx, src/app/ror.org/[rorid]/Content.tsx, src/app/ror.org/[rorid]/page.tsx, src/data/queries/doiQuery.ts, src/data/queries/organizationQuery.ts, src/data/queries/personQuery.ts, src/data/queries/repositoryQuery.ts
=> Remove variables from content

src/data/queries/doiQuery.ts
Fixes an issue with searches that didn't return repository information
Usually OtherDois
Add a couple of ternary operators to catch null values and substitute an appropriate "null repository". 
Additional refactor and formatting
=> Rest doi patch

src/data/color_palettes.ts, src/utils/helpers.ts
Replicates https://github.com/datacite/akita/pull/420 with signed commits.
=> Support Schema 4.6 features

src/data/queries/doiQuery.ts
Don't throw an error if multiple works returned until https://github.com/datacite/datacite/issues/1836 gets resolved
=> don't throw an error if multiple works returned

public/robots.txt
Allows crawling of search tab landing pages to clean up DataCite Commons Google search representation. 
Checked the updated robots.txt against this robots.txt validator and testing tool for Google and Bing crawlers: https://technicalseo.com/tools/robots-txt/ 
=> Allows crawling of search tab landing pages

package.json, src/app/Providers.tsx, src/components/SearchWork/SearchWork.tsx, src/data/queries/doiQuery.ts, src/data/queries/searchDoiFacetsQuery.ts, src/data/queries/searchDoiQuery.ts, src/data/types.ts, src/styles.css, src/utils/helpers.ts, yarn.lock
=> Replace doi search graphql with rest api

src/utils/helpers.ts
Fixes an issue with the processing of the DOI.org URL.  Was not working for client-side fetched data.
closes: #432 
Uses an explicit value for the ID_BASE, and exposes it through a NEXT_PUBLIC_ prefixed environmental variable (which is available client-side).  Fallback to the handle.stage.... url if not set.
=> Make ID_BASE work for client side code as well

cypress/e2e/searchWork.test.ts, src/app/doi.org/page.tsx, src/app/ror.org/[rorid]/mapSearchParams.ts, src/components/WorkFacets/WorkFacets.tsx, src/data/queries/organizationRelatedContentQuery.ts, src/data/queries/searchDoiFacetsQuery.ts, src/data/queries/searchDoiQuery.ts, src/data/types.ts
Adds `Repository Type` facet based on `client.client_type`.
closes: https://github.com/datacite/product-backlog/issues/93
=> Adds `Repository Type` facet based on `client.client_type`

src/app/ror.org/[rorid]/RelatedContent.tsx, src/data/queries/organizationRelatedContentQuery.ts, src/data/queries/searchDoiFacetsQuery.ts, src/data/queries/searchDoiQuery.ts
=> move organization filtering into doi search logic

src/data/queries/doiQuery.ts
=> add detail query parameter

src/app/repositories/[...repoid]/page.tsx, src/components/RepositoryDetail/RepositoryDashboard.tsx, src/components/RepositoryDetail/RepositoryDetail.tsx, src/data/queries/repositoryRelatedContentQuery.ts, src/data/queries/searchDoiFacetsQuery.ts, src/data/queries/searchDoiQuery.ts
=> use REST API for repository related content

src/app/orcid.org/[orcid]/RelatedContent.tsx, src/data/queries/personRelatedContentQuery.ts, src/data/queries/searchDoiFacetsQuery.ts, src/data/queries/searchDoiQuery.ts
=> replace person related works with REST API

package.json, src/app/doi.org/[...doi]/RelatedContent.tsx, src/app/orcid.org/[orcid]/RelatedContent.tsx, src/app/ror.org/[rorid]/RelatedContent.tsx, src/components/Loading/LoadingFacetList.tsx, src/components/SearchWork/SearchWork.tsx, src/components/WorkFacets/WorkFacets.tsx, src/components/WorksListing/WorksListing.tsx, yarn.lock
Improve loading experience for search facets and works listing by adding a loading placeholder for facets.
Implemented a new loading placeholder component for facets using react-content-loader to provide a better user experience during data fetching.
- Added new `LoadingFacetList` component in `src/components/Loading/LoadingFacetList.tsx`
- Updated `WorkFacets` component to use the new loading placeholder
- Modified `WorksListing` and `SearchWork` components to support facet loading state
- Updated `react-content-loader` package to version 7.0.2
- The `LoadingFacetList` component generates randomized placeholder content to mimic the actual facet list layout
- Supports configurable number of facet groups and lines
- Uses dynamic sizing and random width generation to create a more natural …
=> Add loading placeholder for search facets

cypress/e2e/server.test.ts, package.json, src/components/OrganizationMetadata/OrganizationMetadata.module.scss, src/components/OrganizationMetadata/OrganizationMetadata.tsx, src/components/Pager/Pager.tsx, src/components/SearchOrganization/SearchOrganization.tsx, src/data/clients/ror-v2-client.ts, src/data/queries/searchOrganizationQuery.ts, src/utils/helpers.ts, yarn.lock
Improve the organization search functionality by migrating from GraphQL to a direct ROR API V2 client implementation, enhancing search capabilities and data retrieval.
Replaced the existing GraphQL-based organization search with a new ROR V2 API client that provides more flexible and direct data fetching. The changes include:
- Created a new ROR V2 API client (`ror-v2-client.ts`) with type-safe interfaces
- Updated `searchOrganizationQuery.ts` to use the new ROR client
- Added country and organization type mapping utilities
- Implemented caching and query management with React Query
- Enhanced organization metadata rendering
- Updated component rendering for organization search results
- Implemented a robust error handling mechanism for API requests
- Added support for pagination and …
=> Migrate Organization Search to ROR V2 API Client

src/components/FacetList/FacetListGroup.module.scss, src/components/SearchOrganization/SearchOrganization.tsx, src/components/SearchRepository/SearchRepository.tsx, src/components/WorksListing/WorksListing.tsx
=> Adds uniform horizontal spacing to facets list based on the container

cypress/e2e/personContainer.test.ts, cypress/e2e/searchOrganization.test.ts, cypress/e2e/searchWork.test.ts, src/components/FacetList/FacetList.module.scss, src/components/FacetList/FacetList.tsx, src/components/FacetList/FacetListGroup.module.scss, src/components/FacetList/FacetListGroup.tsx, src/components/FacetList/FacetListItem.module.scss, src/components/FacetList/FacetListItem.tsx, src/components/FairFilter/FairFilter.tsx, src/components/SearchBox/SearchBox.tsx, src/components/SearchOrganization/SearchOrganization.tsx, src/components/SearchRepository/SearchRepository.tsx, src/components/WorkFacets/WorkFacets.tsx
Refactor and improve the facet list and search components to enhance user experience and code maintainability.
Redesign the facet list components to use Bootstrap's Accordion for better organization and interactivity. Improve styling, accessibility, and component structure across search-related components.
- Introduced `FacetListGroup` component using Bootstrap Accordion
- Refactored `FacetList` and `FacetListItem` components
- Updated styling with SCSS modules
- Improved type safety and component props
- Simplified search and facet rendering in multiple components
- Used React Bootstrap Accordion for facet list rendering
- Implemented custom styling with SCSS modules
- Added default active keys for facet groups
- Improved type annotations and component interfaces
- Removed redundant Row …
=> Refactor Facet List Components with Bootstrap Accordion

src/components/Header/ServerButtons.tsx
This PR updates the `ServerButtons` component to use Next.js `Link` component for internal navigation. This change aims to improve the application's performance and user experience by enabling client-side navigation.
The `NavLink` components within `ServerButtons` are updated to utilize the `as` prop to wrap the links with Next.js's `Link` component. This allows for client-side transitions between pages instead of full page reloads.
-   Imported `Link` from `next/link`.
-   Added `as={Link}` to the `NavLink` components within `WorksLink`, `PeopleLink`, `OrganizationsLink`, and `RepositoriesLink`.
-   Using Next.js's `Link` component ensures that navigation between internal pages is handled on the client-side. This results in faster transitions and a more responsive user interface because …
=> `ServerButtons`: Use Next.js `Link` for navigation

src/styles.css
Improve scrollbar behavior and layout stability across different browsers and content lengths.
Added CSS properties to provide a consistent scrollbar experience and prevent layout shifts by ensuring a stable scrollbar presence.
- Added `scrollbar-gutter: stable` to HTML element to reserve scrollbar space
- Added `overflow-y: scroll` to HTML element to always show vertical scrollbar
- Set `scrollbar-width: auto` on body to allow default scrollbar width
- `scrollbar-gutter: stable` prevents content from shifting when scrollbar appears or disappears
- `overflow-y: scroll` ensures vertical scrollbar is always visible
- `scrollbar-width: auto` provides a consistent scrollbar appearance across browsers
- Consider using positive …
=> Customize scrollbar styles for better user experience and prevent layout shifts

src/app/about/page.tsx
This PR updates the link in the about page to point to the roadmap instead of the productboard.
The link in the about page was updated to point to the roadmap.
=> Update About page with DataCite roadmap link

src/app/ror.org/[rorid]/Content.tsx, src/app/ror.org/[rorid]/page.tsx, src/components/Error/Error.tsx, src/components/SummarySearchMetrics/SummarySearchMetrics.tsx, src/data/clients/ror-v2-client.ts, src/data/queries/searchDoiQuery.ts, src/data/queries/searchOrganizationQuery.ts, src/data/queries/searchSummaryQuery.ts
This PR updates the ROR (Research Organization Registry) organization page to improve data fetching, loading states, and metadata display. The changes enhance the user experience by providing more dynamic and responsive organization information.
The changes modify how organization data is fetched and displayed by:
- Switching from server-side to client-side data fetching
- Adding a new hook for fetching ROR organization data
- Implementing a summary metrics component
- Improving error handling and loading states
- Converted `Content.tsx` to a client-side component
- Added `useROROrganization` hook for fetching organization data
- Introduced `SummarySearchMetrics` component
- Updated `Error` component to make message optional
- Enhanced ROR V2 client types and data processing
- Improved …
=> ROR Organization Page with ROR REST API and Client-Side Data Fetching

src/components/DataCiteButton/DataCiteButton.module.scss, src/components/DiscoverWorksAlert/DiscoverWorksAlert.module.scss, src/components/DiscoverWorksAlert/DiscoverWorksAlert.tsx, src/components/DownloadMetadata/DownloadMetadata.tsx, src/components/ExampleText/ExampleText.tsx
=> Orcid tweaks
